services:
  admin:
    image: nikolai-backend-admin:local
    platform: linux/amd64
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: admin

  daily-lexika:
    image: nikolai-backend-daily-lexika:local
    platform: linux/amd64
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: daily-lexika
