services:

  db:
    container_name: nikolai-backend-db
    image: 'postgres:16.2-alpine'
    restart: always
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
      - ../postgresql/logs:/var/log/postgresql/pg_log
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "log_directory=/var/log/postgresql/pg_log",
               "-c", "logging_collector=on",
               "-c", "log_filename=postgresql-%Y-%m-%d.log",
               "-c", "log_rotation_age=1d",
               "-c", "log_rotation_size=0" ]
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"

  admin:
    platform: linux/amd64
    container_name: nikolai-backend-admin
    image: docker.io/${DOCKERHUB_NAMESPACE}/nikolai-backend-admin:${APP_TAG}
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DAILY_LEXIKA_BASE_URL: ${DAILY_LEXIKA_BASE_URL}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}


  daily-lexika:
    platform: linux/amd64
    container_name: nikolai-backend-daily-lexika
    image: docker.io/${DOCKERHUB_NAMESPACE}/nikolai-backend-daily-lexika:${APP_TAG}
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DAILY_LEXIKA_BASE_URL: ${DAILY_LEXIKA_BASE_URL}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
