services:
  db:
    ports:
      - "5432:5432"

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile

  daily-lexika:
    build:
      context: .
      dockerfile: daily-lexika/Dockerfile
