server:
  port: 8085

spring:
  application:
    name: vocabulary
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: 'postgres'
    password: '1478236950'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchanges:
    vocabulary: vocabulary.exchange
  queues:
    delete-chinese-flashcards: vocabulary.delete-chinese-flashcards.queue
  routing-keys:
    delete-chinese-flashcards: vocabulary.delete-chinese-flashcards.routing-key

file-location:
  data-excel: "backend/vocabulary/src/main/resources/static/data/Data.xlsx"